config/routes.rb
Rails.application.routes.draw do
  get '/welcome', to: "welcome#home", as: "welcome_page"
  root to: "welcome#home"

  delete '/cookbook_recipe_delete/:recipe_id/:id', to: "cookbook_recipes#destroy", as: "delete_cookbook_recipe"
  devise_for :users, controllers: { :omniauth_callbacks => "callbacks"}


  resources :recipes
  resources :cookbooks

  resources :cookbooks, only: [:show] do
    resources :recipes, only: [:new, :show, :index, :edit, :update, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cookbook.rb
class Cookbook < ApplicationRecord
  belongs_to :user
  has_many :cookbook_recipes, dependent: :destroy
  has_many :recipes, :through => :cookbook_recipes

  validates :title, presence: true
  validates :author, presence: true


  def self.traditional_cookbooks
    where('creation_date <= 1970')
  end

  def self.modern_cookbooks
    where('creation_date >= 1971')
  end

  def self.foreign_cuisine_cookbooks
    where('creation_date >= 2000')
  end

  def self.other_cookbooks
    where('creation_date >= 2020')
  end

  def recipes_attributes=(recipe)
    if recipe[:name] != "" && recipe[:ingredients] != "" &&
       recipe[:cook_method] != "" && recipe[:difficulty] != ""
       new_recipe = self.recipes.build
       new_recipe.name = recipe[:name]
       new_recipe.ingredients = recipe[:ingredients]
       new_recipe.cook_method = recipe[:cook_method]
       new_recipe.difficulty = recipe[:difficulty]
    end
  end
end

app/models/cookbook_recipe.rb
class CookbookRecipe < ApplicationRecord
  belongs_to :cookbook
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :cookbook_recipes, dependent: :destroy
  has_many :cookbooks, :through => :cookbook_recipes

  validates :name, presence: true



  def cookbook_recipes_attributes=(cookbook_recipe)
    if !cookbook_recipe[:prep_time].blank? || !cookbook_recipe[:cook_time].blank?
      self.save if self.id.nil?
      new_cookbook_recipe = self.cookbook_recipes.find_or_create_by(cookbook_id: cookbook_recipe["cookbook_id"].to_i, recipe_id: self.id)
      new_cookbook_recipe.update(prep_time: cookbook_recipe[:prep_time], cook_time: cookbook_recipe[:cook_time])
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  devise :omniauthable, :omniauth_providers => [:facebook]

  has_many :cookbooks

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.name = auth.info.name
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password])
  end
end

app/controllers/callbacks_controller.rb
class CallbacksController < ApplicationController

  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]

      
      # render allows variables defined in facebook action to be maintained
      render new_user_registration_url
    end
  end

  def failure
    redirect_to new_user_registration_url
  end


end

app/controllers/cookbook_recipes_controller.rb
class CookbookRecipesController < ApplicationController
  def destroy
    @cookbook_recipe = CookbookRecipe.find_by(cookbook_id: params[:recipe_id], recipe_id: params[:id])
    @cookbook_recipe.destroy
    redirect_to cookbook_path((current_user.cookbooks.find_by(id: params[:recipe_id])))
  end
end

app/controllers/cookbooks_controller.rb
class CookbooksController < ApplicationController
  before_action :set_cookbook, only: [:show, :edit, :update, :destroy]

  def index
    if user_signed_in?
      @cookbooks = current_user.cookbooks
    else
      redirect_to new_user_session_path
    end
  end

  def new
    @cookbook = current_user.cookbooks.build
  end

  def create
      @cookbook = current_user.cookbooks.build(cookbook_params)
       if @cookbook.save
         redirect_to cookbooks_path
      else
        render new_cookbook_path
   end
 end

  def show
  end

  def edit
  end

  def update
    if @cookbook.update(cookbook_params)
     redirect_to cookbook_path
   else
     render :edit
   end
  end

  def destroy
    @cookbook.destroy
    redirect_to cookbooks_path
  end

  private

    def cookbook_params
      params.require(:cookbook).permit(
        :title,
        :author,
        recipe_ids: [],
      )
    end

    def set_cookbook
      @cookbook = Cookbook.find_by(id: params[:id])
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  before_action :set_cookbook, only: [:new, :show, :edit]
  before_action :set_cookbook_recipe, only: [:show, :edit, :update]

    def index
      if user_signed_in?
        @recipes = Recipe.all
      else
        redirect_to new_user_session_path
     end
   end

   def new
     @recipe = @cookbook.recipes.build
     @recipe.cookbook_recipes.build
   end

   def create
     cookbook_id = recipe_params["cookbook_recipes_attributes"]["cookbook_id"]
     @cookbook = Cookbook.find_by(id: cookbook_id)
     @recipe = @cookbook.recipes.build(recipe_params)
     if @recipe.save
       redirect_to cookbook_path(@cookbook)
     else
       render :new
     end
   end

   def show
   end

   def edit
   end

   def update
     if @recipe.update(recipe_params)
       cookbook_id = @recipe.cookbook_recipes.all.last.cookbook_id
       @cookbook = current_user.cookbooks.find_by(id: cookbook_id)
       redirect_to cookbook_recipe_path(@cookbook, @recipe)
     else
       render :edit
     end
   end

   def destroy
     @recipe.destroy
     redirect_to cookbooks_path
   end


 private
   def recipe_params
     params.require(:recipe).permit(
       :name,
       :ingredients,
       :cook_method,
       :difficulty,
       cookbook_recipes_attributes: [
         :id,
         :cookbook_id,
         :cook_time,
         :prep_time
       ]
     )
   end

   def set_recipe
     @recipe = Recipe.find_by(id: params[:id])
   end

   def set_cookbook
     @cookbook = current_user.cookbooks.find_by(id: params[:cookbook_id])
   end

   def set_cookbook_recipe
     @cookbook_recipe = CookbookRecipe.find_by(cookbook_id: params[:cookbook_id], recipe_id: params[:id])
   end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

def home
   redirect_to cookbooks_path if user_signed_in?
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cookbook_recipes_helper.rb
module CookbookRecipesHelper
end

app/helpers/cookbooks_helper.rb
module CookbooksHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/cookbooks/_form.html.erb
<% if cookbook.errors.any? %>
  <h5 class="error"><%= cookbook.errors.full_messages.to_sentence %></h5>
<% end %>

<%= form_with model: cookbook, local: true do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, class: cookbook.errors.any? ? "error-field" : nil %>
  <br>
  <br>

  <%= f.label :author %>
  <%= f.text_field :author, class: cookbook.errors.any? ? "error-field" : nil %>
  <br>
  <br>
  <%= f.label :creation_date %>
  <%= f.number_field :creation_date, class: cookbook.errors.any? ? "error-field" : nil %>
  <br>
  <br>
  <br><br>

  <h3>Add Some Existing Recipes</h3>
  <%= f.collection_check_boxes :recipe_ids, Recipe.all, :id, :name do |e| %>
    <%= e.check_box %>
    <%= e.object.name %>
    <br>
  <% end %>
  <br>



<%= f.submit class: "submit-link" %>
<% end %>

app/views/cookbooks/edit.html.erb
<!--<a href="<%= cookbooks_path %>"><%= current_user.name %>'s Cookbooks</a> > <a href="<%= cookbook_path(@cookbook) %>"><%= @cookbook.title %></a> > Edit
-->
<h1>Edit Cookbook</h1>
<%= render "cookbooks/form", cookbook: @cookbook %>

app/views/cookbooks/index.html.erb
<h1>Hi, <%= current_user.name %>!</h1>

<%= link_to "Create Cookbook", new_cookbook_path, class: "submit-link" %>


<h4>Filter by: </h4>
<%= form_tag cookbooks_path, method: "get" do %>
  <%= select_tag "cookbook", options_for_select(["Traditional", "Modern", "Foreign Cuisine", "Other"]), include_blank: true %>
  <%= submit_tag "Filter" %>
<% end %>

<% if !params[:cookbook].blank? %>
  <% if params[:cookbook] == "Traditional" %>
    <% @cookbooks = Cookbook.traditional_cookbooks %>
    <h3>Traditional Cookbooks</h3>
  <% elsif params[:cookbook] == "Modern" %>
    <% @cookbooks = Cookbook.modern_cookbooks %>
    <h3>Modern Cookbooks</h3>
  <% elsif params[:cookbook] == "Foreign Cuisine" %>
    <% @cookbooks = Cookbook.foreign_cuisine_cookbooks %>
    <h3>Foreign Cuisine Cookbooks</h3>
    <% elsif params[:cookbook] == "Other" %>
      <% @cookbooks = Cookbook.other_cookbooks %>
      <h3>Other Cookbooks</h3>
  <% end %>
<% end %>


<br>

<h2>List of Cookbooks</h2>

<div id="cookbook-cards">
  <% @cookbooks.each do |cookbook| %>
    <%= link_to cookbook.title, cookbook_path(cookbook), class: "cookbook-card" %> <br> <br>
  <% end %>
</div>

<%= link_to "Sign out", destroy_user_session_path, id: "signout-link", method: :delete %>

app/views/cookbooks/new.html.erb
<%= link_to "#{current_user.name}'s Cookbooks", cookbooks_path %>

<h1>New Cookbook</h1>
<%= render "cookbooks/form", cookbook: @cookbook %>

app/views/cookbooks/show.html.erb
<div class="navbar">
  <nav>
    <a href="<%= cookbooks_path %>"><%= current_user.name %>'s Cookbooks</a> > <%= @cookbook.title %> <br />
  </nav>
</div>
<br><br>


<h1><%= @cookbook.title %></h1>
Author:  <strong><%= @cookbook.author %></strong>


<br>
<br>

<%= link_to "Create Recipe for Cookbook", new_cookbook_recipe_path(@cookbook, @recipe) %> <br>

    <div id="recipe-cards">

      <% @cookbook.recipes.uniq.each do |recipe| %>
        <div class="recipe-card">
          <%= link_to recipe.name, cookbook_recipe_path(@cookbook, recipe) %>
        </div>
      <% end %>
    </div>

    <br>
    <div class="crud-links">
      <%= link_to "Edit Cookbook", edit_cookbook_path(@cookbook), class: "edit-link" %> <br>
      <%= link_to "Delete Cookbook", @cookbook, class: "delete-link", method: :delete %>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyRecipeApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/_form.html.erb
<% if recipe.errors.any? %>
  <h5 class="error"><%= recipe.errors.full_messages.to_sentence %></h5>
<% end %>

<%= form_with model: recipe, local: true do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name, class: recipe.errors.any? ? "error-field" : nil %>
  <br>

  <%= f.label :ingredients %>
  <%= f.text_field :ingredients %>
  <br>

  <%= f.label :cook_method %>
  <%= f.text_area :cook_method %>
  <br>

  <%= f.label :difficulty %>
  <%= f.number_field :difficulty %>
  <br><br>

  <%= f.fields_for :cookbook_recipes_attributes do |ref| %>
    <%= ref.hidden_field :cookbook_id, value: params[:cookbook_id] %>
    <%= ref.label :cook_time %>
    <%= ref.number_field :cook_time, placeholder: "#{@recipe.cookbook_recipes.last.cook_time}" %>
    <br>

    <%= ref.label :prep_time %>
    <%= ref.number_field :prep_time, placeholder: "#{@recipe.cookbook_recipes.last.prep_time}" %>

    <br>
  <% end %>
  <%= f.submit class: "submit-link" %>
<% end %>

app/views/recipes/edit.html.erb
<% if @recipe.errors.any? %>
  <h5 class="error"><%= recipe.errors.full_messages.to_sentence %></h5>
  <br>
<% end %>

<h1>Edit Recipe</h1>

<%= render "recipes/form", recipe: @recipe %>

app/views/recipes/index.html.erb
<h1>Hi, <%= current_user.name %>!</h1>

<%= link_to "Create Recipe", new_recipe_path, class: "submit-link" %>


<br>

<h2>List of All Recipes</h2>

<div id="recipe-cards">
  <% @recipes.each do |recipe| %>
    <%= link_to recipe.name, recipe_path(recipe), class: "recipe-card" %> <br> <br>
  <% end %>
</div>

<%= link_to "Sign out", destroy_user_session_path, id: "signout-link", method: :delete %>

app/views/recipes/new.html.erb
<%= link_to "#{current_user.name}'s Recipes", cookbook_path(@cookbook) %>

<h1>New Recipe</h1>
<%= render "recipes/form", recipe: @recipe %>

app/views/recipes/show.html.erb
<div class="navbar">

  <nav>
    <a href="<%= cookbooks_path %>"><%= current_user.name %>'s Cookbooks </a> > <a href="<%= cookbook_path(@cookbook) %>"><%= @cookbook.title %></a> > <%= @recipe.name %> <br />
  </nav>
</div>
<br><br>
<h1><%= @recipe.name %></h1>
<strong>Ingredients: </strong><%= @recipe.ingredients %><br>
<strong>Cook Method: </strong><%= @recipe.cook_method %><br>
<strong>Difficulty: </strong><%= @recipe.difficulty %><br>


<strong>Cook Time: </strong><%= @cookbook_recipe.cook_time %><br>
<strong>Prep Time: </strong><%= @cookbook_recipe.prep_time %><br>
<br>



<div class="crud-links">
  <%= link_to "Edit Recipe", edit_cookbook_recipe_path(@cookbook, @recipe), class: "edit-link" %> <br>
  <%= link_to "Delete Recipe", "/recipes/#{@recipe.id}", class: "delete-link", method: :delete %>
</div>

app/views/welcome/home.html.erb
<h1>Welcome to My Recipes App!</h1>

<%= image_tag "pasta_pic.jpeg"%>

<br> <br>
<div id="home-page-links">
  <%= link_to "Sign Up", new_user_registration_path, id: "signup-link" %>
  <%= link_to "Log In", new_user_session_path, id: "regular-login-link" %>
</div>